export type TemplateSample = {
  slug: string;
  classCode: string;
  templateClass: string;
  group: 'Performance' | 'SEO / Authority' | 'Mid-funnel / Nurturing' | 'System / Utility';
  theme: 'performance' | 'authority' | 'nurture' | 'system';
  pageRole: string;
  description: string;
  audience: string;
  funnel: string;
  traffic: string;
  cvr: string;
  primaryCta: string;
  secondaryCta: string;
  sampleHeadline: string;
  sampleBody: string;
  previewHighlights: string[];
  blockOrder: string[];
  brandRules: string[];
  seoRules: string[];
  enhancementIdeas: string[];
  internalLinks: { title: string; href: string; body: string }[];
};

export const templateSamples: TemplateSample[] = [
  {
    slug: 'class-a-fee-capture',
    classCode: 'Class A',
    templateClass: 'Fee Capture Landing',
    group: 'Performance',
    theme: 'performance',
    pageRole: 'Doi bang hoc phi chi tiet lay lead chat luong',
    description:
      'Sample nay minh hoa mot landing page performance nhung van giu brand tone cua Viet Anh: ro gia tri, ro buoc tiep theo, khong giat gan va khong lam re thuong hieu.',
    audience: 'Phu huynh dang tim hoc phi theo cap hoc / khu vuc',
    funnel: 'BOFU',
    traffic: 'Google Search Ads, Meta Lead Ads, Zalo Ads, branded commercial queries',
    cvr: '12-18%',
    primaryCta: 'Nhan bang hoc phi',
    secondaryCta: 'Nhan Zalo tu van',
    sampleHeadline: 'Nhan bang hoc phi chi tiet de so sanh trong vai phut, khong can phai doan.',
    sampleBody:
      'Landing nay can noi dung ro, ngan, minh bach vua du va co trust that. Hero phai cho phu huynh thay ngay gia tri nhan duoc va CTA can rat cu the.',
    previewHighlights: [
      'Headline khop voi intent hoc phi, khong khoa truong.',
      'Fee snapshot chi nhan manh range, khong day user vao me cung thong tin.',
      'Trust blocks phai la review that, proof that, hotline that.',
      'Form ngan va follow-up ro rang qua thank-you page.',
    ],
    blockOrder: [
      'Hero message match voi heading ngan, trust mini va CTA chinh.',
      'Fee snapshot table de user co moc tham chieu ro rang.',
      'Trust metrics + review phu huynh de tao niem tin truoc form.',
      'Objection block ngan tra loi cau hoi “hoc phi co dang khong?”.',
      'Form short 3-4 field + consent.',
      'FAQ compact va sticky Zalo / hotline.',
    ],
    brandRules: [
      'Dung giong thuc dung: noi ro nhan duoc gi sau khi submit.',
      'Khong dung urgency gia tao, khong “co hoi duy nhat”.',
      'Visual nen it nhung dung: trust, campus that, phu huynh that.',
      'CTA phai lich su va ro nghia, khong ep mua.',
    ],
    seoRules: [
      'Title va description phai match y dinh hoc phi + cap hoc / khu vuc.',
      'Can co H1 duy nhat, schema FAQ neu co FAQ compact.',
      'Internal links chi han che sang /hoc-phi, /tuyen-sinh va page campus lien quan.',
      'Anh nhe, alt ro nghia va content khong qua dai o hero.',
    ],
    enhancementIdeas: [
      'Them variant theo level va campus de dung message match hon.',
      'Noi thank-you page voi PDF delivery va event tracking theo form type.',
      'Test A/B giua CTA “Nhan bang hoc phi” va “Xem hoc phi chi tiet”.',
    ],
    internalLinks: [
      { title: 'Money Page', href: '/hoc-phi', body: 'Trang minh bach de user muon doc them truoc khi submit.' },
      { title: 'Admissions Hub', href: '/tuyen-sinh', body: 'Diem re nhanh cho user muon goi / chat ngay.' },
      { title: 'Template listing', href: '/mau-template/', body: 'Quay lai danh sach mau de review toan he thong.' },
    ],
  },
  {
    slug: 'class-b-campus-tour',
    classCode: 'Class B',
    templateClass: 'Campus Tour / Local Admission Landing',
    group: 'Performance',
    theme: 'performance',
    pageRole: 'Dat lich tham quan va tang lead quality',
    description:
      'Template sample nay dua trust dia phuong, map, gallery va booking flow vao cung mot landing de rut ngan duong tu quan tam sang tham quan thuc te.',
    audience: 'Phu huynh o gan campus muon xem truong that',
    funnel: 'MOFU -> BOFU',
    traffic: 'PMax local, Zalo radius ads, local search, Maps intent',
    cvr: '8-14%',
    primaryCta: 'Dat lich tham quan',
    secondaryCta: 'Xem duong di den truong',
    sampleHeadline: 'Neu gia dinh muon thay bang mat that, hay bat dau tu mot lich tham quan ro rang va de dat.',
    sampleBody:
      'Tour landing khong can noi qua nhieu tri ly. No can cho thay campus that, duong di that, review that va mot CTA dat lich rat de thao tac tren mobile.',
    previewHighlights: [
      'Hero phai dung anh hoac video campus that, khong dung stock photo.',
      'Map va chi duong phai nam rat som tren trang.',
      'Campus highlights phai cuc cu the theo dia diem.',
      'Booking block can ngan, chot duoc ngay va gio.',
    ],
    blockOrder: [
      'Hero campus-specific voi dia chi, hotline va CTA dat lich.',
      'Google Map + nut chi duong.',
      'Campus highlights va gallery that.',
      'Calendar booking block de chot hanh dong.',
      'Review carousel rieng cho co so.',
      'Final CTA + hotline / Zalo sticky.',
    ],
    brandRules: [
      'Giong dieu can gan gui, nhieu bang chung va rat doi thuong.',
      'Khong corporate qua muc, khong mo ta generic nhu moi campus deu giong nhau.',
      'Phai giu brand me o navy/gold nhung noi dung van rat local.',
      'Hinh anh va dia chi phai chinh truc tuyet doi.',
    ],
    seoRules: [
      'Can title local ro rang, co ten co so va khu vuc.',
      'Them local business cues, map, hotline, address vao content som.',
      'Internal links toi pillar page va money page cua level lien quan.',
      'Toi uu mobile va Core Web Vitals vi user thuong vao tu ads / maps.',
    ],
    enhancementIdeas: [
      'Them Google review pull-in thuc te tu campus khi schema san sang.',
      'Cho phep dat slot theo campus qua Directus + lich dong bo.',
      'Them testimonial video ngan quay tai co so do de tang local trust.',
    ],
    internalLinks: [
      { title: 'Tuyen Sinh', href: '/tuyen-sinh', body: 'Admissions hub de tiep tuc hanh dong neu chua dat lich ngay.' },
      { title: 'Mam Non', href: '/mam-non', body: 'Vi du ve pillar page co the dan ve tour landing.' },
      { title: 'Hoc Phi', href: '/hoc-phi', body: 'Bo sung money intent neu phu huynh muon xac minh range chi phi.' },
    ],
  },
  {
    slug: 'class-c-open-day',
    classCode: 'Class C',
    templateClass: 'Open Day / Event Landing',
    group: 'Performance',
    theme: 'performance',
    pageRole: 'Gom dang ky su kien theo dot va tao FOMO co kiem soat',
    description:
      'Sample nay cho thay mot event landing dung gi tinh than Viet Anh: urgency vua du, rat ro ve gia tri su kien, khong dung ki thuat ep mua re tien.',
    audience: 'Phu huynh dang can ly do de den truong trong mot dip cu the',
    funnel: 'MOFU / BOFU',
    traffic: 'Meta, Instagram, event promotion, email, retargeting',
    cvr: '10-16%',
    primaryCta: 'Dang ky tham du',
    secondaryCta: 'Xem lich chuong trinh',
    sampleHeadline: 'Mot su kien tot khong chi gom lead, ma phai giup phu huynh cam thay “di den la dang”.',
    sampleBody:
      'Open Day page can gom du FOMO, du thong tin va du trust. Neu thieu timeline, thieu guest value hoac thieu visual thuc, conversion se rot du da co traffic.',
    previewHighlights: [
      'Countdown can di kem ly do du de den, khong chi de dem nguoc.',
      'Timeline phai cu the de phu huynh hinh dung duoc trai nghiem.',
      'Video nam truoc neu co se nang trust rat manh.',
      'Registration form ngan va phan hoi sau submit phai ro.',
    ],
    blockOrder: [
      'Hero su kien + countdown.',
      'Timeline va highlights cua event.',
      'Guest speakers / hoat dong trai nghiem.',
      'Video hoặc hinh anh event gan day.',
      'Registration form + reminder note.',
      'FAQ compact + final CTA.',
    ],
    brandRules: [
      'Viet urgency mot cach lich su, khong “shock” hay “chot gap”.',
      'Noi ro phu huynh va con nhan duoc gi khi tham gia.',
      'Visual phai that, co khong khi hoc duong va gia dinh.',
      'Giọng dieu am ap, ro rang, co bang chung.',
    ],
    seoRules: [
      'Title can co ten event, year, campus neu co.',
      'Meta description nen noi gia tri su kien va doi tuong phu hop.',
      'URL gon, dung event slug on dinh.',
      'Can internal links tu homepage, admissions va campus pages lien quan.',
    ],
    enhancementIdeas: [
      'Them calendar save block va reminder consent flow.',
      'Dung social proof theo so luong phu huynh da tham gia cac dot truoc.',
      'Bo sung event FAQ schema neu page co nhiieu Q&A.',
    ],
    internalLinks: [
      { title: 'Homepage', href: '/', body: 'Dieu huong campaign tu hero / events strip.' },
      { title: 'Tuyen Sinh', href: '/tuyen-sinh', body: 'Hub de tiep tuc cho nhom chua san sang dang ky event ngay.' },
      { title: 'Template listing', href: '/mau-template/', body: 'Quay lai library khi can review them class khac.' },
    ],
  },
  {
    slug: 'class-d-trial-class',
    classCode: 'Class D',
    templateClass: 'Trial Class / Hoc Thu Landing',
    group: 'Performance',
    theme: 'performance',
    pageRole: 'Go objection “con co hoa nhap duoc khong?”',
    description:
      'Template sample nay uu tien pain point, proof va booking flow. No phai rat manh ve tam ly phu huynh nhung khong doạ dan.',
    audience: 'Warm audience da xem hoc phi / campus nhung chua submit',
    funnel: 'MOFU / BOFU',
    traffic: 'Retargeting, Zalo follow-up, email, remarketing',
    cvr: '9-15%',
    primaryCta: 'Dang ky hoc thu',
    secondaryCta: 'Nhan Zalo tu van',
    sampleHeadline: 'Con nhut nhat khong phai la ly do de cham lai. Thu nghiem mot buoi hoc that moi giup gia dinh quyet dinh nhanh hon.',
    sampleBody:
      'Hoc thu landing phai xu ly noi so rat cu the. Neu hero noi chung chung, phu huynh se khong tin rang buoi thu nay thuc su giai quyet duoc van de cua con.',
    previewHighlights: [
      'Pain-point hero phai rat doi thuong va thong cam.',
      'Video lop hoc that se quan trong hon 10 doan copy dai.',
      'Calendar chon ngay / gio phai cuc de thao tac.',
      'Testimonial nen la “sau buoi hoc thu con thay the nao”.',
    ],
    blockOrder: [
      'Pain-point hero va CTA booking.',
      'Video / visual lop hoc that.',
      'Lich hoc thu va loi ich cua mot buoi trai nghiem.',
      'Parent testimonial sau hoc thu.',
      'Form chon ngay, gio, campus.',
      'Hotline / Zalo sticky.',
    ],
    brandRules: [
      'Khong doi pain point thanh copy giat gan gay lo lang qua muc.',
      'Phai giu giong am va vung, cho thay su dong hanh that.',
      'Proof can rat doi thuong va dang tin.',
      'CTA phai goi dung next step, khong “chot sale”.',
    ],
    seoRules: [
      'Can H1 cham dung intent hoc thu + level / campus neu co.',
      'Description nen noi loi ich cua buoi trai nghiem, khong chi noi “dang ky ngay”.',
      'Internal link toi campus, pillar va thank-you / next-step pages.',
      'Video / media can toi uu nhe de khong giet mobile speed.',
    ],
    enhancementIdeas: [
      'Them block “phu huynh can chuan bi gi truoc buoi hoc thu”.',
      'Them FAQ ngan ve thoi gian, so nguoi di cung, dinh dang trang phuc.',
      'Tao variant rieng cho “be nhut nhat” va “be moi di hoc lan dau”.',
    ],
    internalLinks: [
      { title: 'Mam Non pillar', href: '/mam-non', body: 'Phu hop neu user can doc sau hon truoc khi booking.' },
      { title: 'Admissions Hub', href: '/tuyen-sinh', body: 'Diem lui an toan neu phu huynh muon xac nhan quy trinh.' },
      { title: 'Money Page', href: '/hoc-phi', body: 'Cho nhom can lam ro hoc phi truoc khi quyet hoc thu.' },
    ],
  },
  {
    slug: 'class-f-tiktok-ugc',
    classCode: 'Class F',
    templateClass: 'TikTok / Reels Mobile-First UGC Landing',
    group: 'Performance',
    theme: 'performance',
    pageRole: 'Chuyen doi traffic video ngan tren mobile',
    description:
      'Sample nay minh hoa mot page mobile-first rat gon, nhan manh call / Zalo, hook text ngan va visual that. No van giu tone thuong hieu, khong “giong landing ban khoa hoc”.',
    audience: 'Phu huynh vao tu TikTok, Reels, story ads',
    funnel: 'TOFU -> MOFU nhanh',
    traffic: 'TikTok Ads, Reels Ads, social creators, mobile-only traffic',
    cvr: '7-12%',
    primaryCta: 'Nhan Zalo ngay',
    secondaryCta: 'Goi hotline',
    sampleHeadline: 'Video ngan phai dan ve mot hanh dong cuc ngan. O day do la Zalo, call va niem tin nhanh.',
    sampleBody:
      'Template nay khong duoc thu nho desktop page. No can duoc thiet ke nhu mot trang mobile-first that su: it chu, nhieu hook, CTA noi bat va trust rat co chon loc.',
    previewHighlights: [
      'Hero video doc 9:16 la tam diem.',
      'Text hook ngan, khong paragraph dai.',
      'Floating Zalo CTA phai luon trong tam tay ngon cai.',
      'Gallery ngan va call sticky gop y cho user hanh dong ngay.',
    ],
    blockOrder: [
      'Hero video vertical.',
      'Hook text ngan 2-3 dong.',
      'Floating Zalo CTA.',
      'Mini gallery / short clips.',
      'Call sticky va proof sieu ngan.',
    ],
    brandRules: [
      'Van phai giu navy + gold va giong dieu lich su.',
      'Khong dung visual “sale” qua tay, khong cham icon loan xa.',
      'Hook duoc phep ngan nhung khong duoc re tien.',
      'Proof phai la canh hoc sinh that / campus that.',
    ],
    seoRules: [
      'Dau la paid page nhưng van can title / description ro nghia.',
      'Anh, video va CSS phai toi uu cuc nhe.',
      'Khong de internal links loang traffic qua nhieu.',
      'Can event tracking cho Zalo click va call click.',
    ],
    enhancementIdeas: [
      'Them variant theo creators / angle noi dung.',
      'Test block proof 1 dong vs 3 bullet trust.',
      'Neu co data du, ca nhan hoa campus gan nhat theo traffic source.',
    ],
    internalLinks: [
      { title: 'Admissions Hub', href: '/tuyen-sinh', body: 'Fallback cho user muon doc sau hon sau khi click social.' },
      { title: 'Homepage', href: '/', body: 'Trang thuong hieu me de xac nhan niem tin.' },
      { title: 'Template listing', href: '/mau-template/', body: 'Xem them cac class performance khac.' },
    ],
  },
  {
    slug: 'class-level-pillar',
    classCode: 'Class 6',
    templateClass: 'Level Pillar',
    group: 'SEO / Authority',
    theme: 'authority',
    pageRole: 'Xay topical authority cho tung cap hoc',
    description:
      'Sample nay dai dien cho 4 pillar pages. No can co depth, internal linking, voice giai thich va CTA mem dung luc, khong bi bien thanh paid landing.',
    audience: 'Phu huynh dang nghien cuu cap hoc va so sanh cac mo hinh',
    funnel: 'TOFU / MOFU',
    traffic: 'Organic search, branded search, assisted traffic',
    cvr: '3-6%',
    primaryCta: 'Xem cap hoc phu hop',
    secondaryCta: 'Nhan tu van',
    sampleHeadline: 'Pillar page phai giai thich du sau de rank, nhung van phai dan user den dung campus va dung CTA.',
    sampleBody:
      'Class nay la cot song SEO cua site. Neu viet qua ban hang, no se mat authority. Neu viet qua brochure, no se mat conversion support.',
    previewHighlights: [
      'Hero triet ly cap hoc + outcomes phai ro.',
      'Curriculum, teacher, PDR, campus list va FAQ phai lien mach.',
      'Internal links sang fee, admissions va campus pages la bat buoc.',
      'Voice giai thich, am nhung co chuyen mon.',
    ],
    blockOrder: [
      'Hero philosophy theo cap hoc.',
      'Curriculum highlights va outcomes.',
      'Teacher / environment proof.',
      'PDR hoac signature asset block.',
      'Campus list va internal link hub.',
      'FAQ + CTA mem.',
    ],
    brandRules: [
      'Khong bien pillar page thanh ad page.',
      'Noi ro trai nghiem hoc sinh, khong chi liet ke chuong trinh.',
      'Dung voice giai thich co chieu sau, khong khoa truong.',
      'Phai the hien du “hanh phuc, thuc dung, tu chu”.',
    ],
    seoRules: [
      'H1 ro, sections co heading logic, internal links day.',
      'Meta title / desc dung intent cap hoc, khong nham voi admissions.',
      'FAQ co the them schema. Content phai co proof va updated cadence.',
      'Anh phai dung cap hoc, dung campus, alt co y nghia.',
    ],
    enhancementIdeas: [
      'Them data-driven campus selector trong hero de route manh hon.',
      'Bo sung author / expert cue cho trust SEO.',
      'Them case studies hoc sinh theo cap hoc de tang depth.',
    ],
    internalLinks: [
      { title: 'Mam Non', href: '/mam-non', body: 'Sample live cho pillar cap hoc o wave 1.' },
      { title: 'Tieu Hoc', href: '/tieu-hoc', body: 'Sample live thu hai de xem cach route sang money page.' },
      { title: 'THPT', href: '/trung-hoc-pho-thong', body: 'Sample live mang outcome / IELTS ro nhat.' },
    ],
  },
  {
    slug: 'class-master-campus-profile',
    classCode: 'Class 7',
    templateClass: 'Master Campus Profile',
    group: 'SEO / Authority',
    theme: 'authority',
    pageRole: 'Local trust page cho tung campus',
    description:
      'Template campus profile can rat that, rat local va rat de book tham quan. Day la noi brand me gap local trust page.',
    audience: 'Phu huynh dang tim truong gan nha va muon xem campus cu the',
    funnel: 'MOFU',
    traffic: 'Local SEO, Maps, branded + local queries',
    cvr: '4-8%',
    primaryCta: 'Dat lich tham quan',
    secondaryCta: 'Goi campus',
    sampleHeadline: 'Campus page khong duoc la “contact page keo dai”. No phai la mot micro-brand page co niem tin dia phuong that.',
    sampleBody:
      'Trang nay phai cho thay dia diem, duong di, anh that, review that va cac cap hoc dang van hanh. Day la “local trust engine” cua toan site.',
    previewHighlights: [
      'Map, address, hotline va campus highlights phai o rat som.',
      'Gallery dung campus, dung cap hoc.',
      'Review neu co phai theo campus, khong xai review tong.',
      'CTA tham quan ro hon CTA doc them.',
    ],
    blockOrder: [
      'Hero campus that.',
      'Address + map + hotline.',
      'Campus features + gallery.',
      'Programs available.',
      'Review carousel by campus.',
      'Booking CTA + related local pages.',
    ],
    brandRules: [
      'Rat that, rat cu the, khong copy-paste giua cac campus.',
      'Giu voice brand me nhung phai co mau local.',
      'Hinh anh phai la campus that va duoc consent.',
      'So lieu, hotline, dia chi phai chinh truc tuyet doi.',
    ],
    seoRules: [
      'Title va H1 can co ten campus + khu vuc.',
      'Schema local/business cues nen san sang cho phase sau.',
      'Internal links sang pillar page level, tuyen sinh va hoc phi.',
      'Content can unique du de tranh duplicate local pages.',
    ],
    enhancementIdeas: [
      'Them section xe dua don / practical information khi data day du.',
      'Tich hop review tu Google neu co cache / moderation.',
      'Them FAQ rieng theo campus khi volume traffic du lon.',
    ],
    internalLinks: [
      { title: 'Homepage', href: '/', body: 'Homepage se dan traffic vao campus pages khi wave 2 live.' },
      { title: 'Admissions Hub', href: '/tuyen-sinh', body: 'Route tiep theo cho user can quy trinh thay vi tour.' },
      { title: 'Money Page', href: '/hoc-phi', body: 'Diem re cho nhom can xac nhan cost sau khi thay campus.' },
    ],
  },
  {
    slug: 'class-local-intent',
    classCode: 'Class 8',
    templateClass: 'Local Intent Landing',
    group: 'SEO / Authority',
    theme: 'authority',
    pageRole: 'Bat local query dai va dan ve campus dung',
    description:
      'Sample nay minh hoa local SEO page khong bi bien thanh doorway page. Noi dung phai co enough unique local proof, enough utility va CTA ro rang.',
    audience: 'Phu huynh tim truong gan khu vuc / landmark cu the',
    funnel: 'MOFU / BOFU',
    traffic: 'Local organic, adjacent-area queries, local ads',
    cvr: '5-9%',
    primaryCta: 'Xem co so phu hop',
    secondaryCta: 'Tu van ngay',
    sampleHeadline: 'Local intent page tot phai tra loi duoc “gan ai, gan dau, phu hop cho cap hoc nao” trong vai giay dau.',
    sampleBody:
      'Template nay can ket hop query-local match, proof local va routing chuan ve campus that. Neu chi thay slug va thay ten quan, no se thanh doorway page.',
    previewHighlights: [
      'Hero dynamic local phai co ten khu vuc / landmark ro.',
      'Quick answer block giai quyet y dinh tim kiem ngay.',
      'Review va proof can local hon homepage.',
      'CTA phai dan ve campus that va money / admissions support.',
    ],
    blockOrder: [
      'Dynamic local hero.',
      'Quick answer block.',
      'Program + facility summary.',
      'Local proof / review.',
      'Form short / CTA short.',
      'Related campus va pillar links.',
    ],
    brandRules: [
      'Giu gin chinh truc: khong tao local page ma khong co proof thuc.',
      'Noi dung phai co chat luong utility, khong spin SEO vo hon.',
      'Voice can ro, gan gui, binh tinh.',
      'Van giu brand me, khong tach thanh “website khac”.',
    ],
    seoRules: [
      'Can unique 15%+ noi dung va local proof ro rang.',
      'Title / H1 nen chua level + area.',
      'Internal links bat buoc toi campus page, pillar va money / admissions.',
      'Can tranh duplicate mo ta giua cac local pages.',
    ],
    enhancementIdeas: [
      'Them block “tu khu vuc nay den campus mat bao lau”.',
      'Su dung landmark-aware copy va map snippet cho long-tail manh hon.',
      'Scale programmatic sau khi da co bo local data du chat luong.',
    ],
    internalLinks: [
      { title: 'Master Campus Profile', href: '/mau-template/class-master-campus-profile/', body: 'Template ban goc ma local page can route ve.' },
      { title: 'Level Pillar', href: '/mau-template/class-level-pillar/', body: 'Authority layer phia sau local query.' },
      { title: 'Admissions Hub', href: '/tuyen-sinh', body: 'Diem chot hanh dong neu phu huynh san sang.' },
    ],
  },
  {
    slug: 'class-parent-hub-article',
    classCode: 'Class 9',
    templateClass: 'Parent Hub Article',
    group: 'Mid-funnel / Nurturing',
    theme: 'nurture',
    pageRole: 'Keo SEO thong tin va nuoi trust',
    description:
      'Template blog / parent hub phai co chieu sau, giup ich that va van giu duoc internal links + CTA mem. No la noi brand voice duoc the hien rat ro.',
    audience: 'Phu huynh dang tim hieu mot van de giao duc cu the',
    funnel: 'TOFU / MOFU',
    traffic: 'Organic informational, PAA, social sharing',
    cvr: '2-5%',
    primaryCta: 'Xem chuong trinh phu hop',
    secondaryCta: 'Nhan tu van mem',
    sampleHeadline: 'Bai viet phu huynh hub tot phai giup truoc, ban sau. Neu khong, no se thanh content farm.',
    sampleBody:
      'Template nay duoc xay de co TOC, heading dang cau hoi, in-content CTA mem va authorial confidence. No phai giong mot tai lieu huu ich, khong phai bai PR dien hinh.',
    previewHighlights: [
      'TOC va heading question-based la bat buoc.',
      'In-content CTA mem chi xuat hien khi da cho user du gia tri.',
      'Author box va updated date giup trust hon.',
      'Internal links nen dat ve pillar, campus va FAQ / admissions lien quan.',
    ],
    blockOrder: [
      'Title + intro answer-first.',
      'TOC.',
      'Noi dung sau theo heading logic.',
      'In-content CTA banner.',
      'Related posts.',
      'Author box + updated date.',
    ],
    brandRules: [
      'Viet am, co chieu sau va khong phan xet phu huynh.',
      'Khong spam ten truong qua muc trong moi doan.',
      'Van phai cho thay triet ly hanh phuc, thuc dung, tu chu.',
      'Khong dung fear-based copy de “ep” doc them.',
    ],
    seoRules: [
      'Title phai dung intent cau hoi / guide.',
      'Can TOC, heading ro, internal links va FAQ neu hop ly.',
      'Anh ho tro vua du, alt dung nghia.',
      'Meta description nen noi ro user se hoc duoc gi.',
    ],
    enhancementIdeas: [
      'Them author entity that su tu doi ngu giao vien / co van.',
      'Bo sung infographic / checklist download cho cluster quan trong.',
      'Xay content clusters co related posts theo cap hoc va topic.',
    ],
    internalLinks: [
      { title: 'Level Pillar', href: '/mau-template/class-level-pillar/', body: 'Dich den authority page phia sau bai viet.' },
      { title: 'AI-Ready FAQ', href: '/mau-template/class-ai-ready-faq/', body: 'Bo sung answer engine cho long-tail va PAA.' },
      { title: 'Admissions Hub', href: '/tuyen-sinh', body: 'CTA mem co the route user ve admissions khi da du trust.' },
    ],
  },
  {
    slug: 'class-comparison-engine',
    classCode: 'Class 10',
    templateClass: 'Comparison Engine Page',
    group: 'Mid-funnel / Nurturing',
    theme: 'nurture',
    pageRole: 'Xu ly giai doan can nhac va so sanh',
    description:
      'Sample comparison page phai binh tinh, logic va co proof. No khong duoc cong kich doi thu, nhung van phai giup phu huynh thay duoc khac biet cua Viet Anh.',
    audience: 'Phu huynh dang can nhac giua cac mo hinh truong',
    funnel: 'MOFU',
    traffic: 'SEO comparison, retargeting, sales follow-up',
    cvr: '4-7%',
    primaryCta: 'Nhan tu van de chon phu hop',
    secondaryCta: 'Xem hoc phi',
    sampleHeadline: 'Comparison page tot giup phu huynh quyet dinh tinh tao hon, khong phai bi thuyet phuc bang slogan.',
    sampleBody:
      'Trang nay can co dynamic comparison table, unique points, FAQ va CTA mem. Voice phai calm confidence, minh bach va dung tinh than chinh truc cua brand.',
    previewHighlights: [
      'Bang so sanh phai de doc tren mobile.',
      'Unique points cua Viet Anh can noi bang ngon ngu khong tu ton phong dai.',
      'FAQ giup xu ly tu nhung objection hay gap.',
      'CTA nen route ve consultation hoac money page, khong ep chot gap.',
    ],
    blockOrder: [
      'Comparison hero.',
      'Comparison table.',
      'Unique points cua Viet Anh.',
      'FAQ compact.',
      'CTA + internal links.',
    ],
    brandRules: [
      'Khong dung tu “so 1”, “tot nhat”, “duy nhat” neu khong co proof.',
      'Khong viet theo huong bieu xau doi thu.',
      'Nhan manh khac biet ve PDR, hanh phuc, tu chu, tieng Anh thuc chien.',
      'Giữ giong logic, khong phong thu qua muc.',
    ],
    seoRules: [
      'Title can match so-sanh intent ro rang.',
      'Table co the duoc render bang HTML semantic de may tim kiem doc tot.',
      'FAQ + internal links sang pillars, hoc phi, admissions la bat buoc.',
      'Can unique opening copy, khong tao hang loat page nhan ban vo hon.',
    ],
    enhancementIdeas: [
      'Them dynamic data source tu Directus de scale cac trang so sanh.',
      'Cho phep hide / show cot tren mobile.',
      'Co moderation layer cho competitor data de tranh stale.',
    ],
    internalLinks: [
      { title: 'Dynamic Comparison', href: '/mau-template/class-dynamic-comparison/', body: 'Phien ban scale du lieu dong cua template so sanh.' },
      { title: 'Objection Handler', href: '/mau-template/class-objection-handler/', body: 'Template tiep theo cho giai doan do du sau.' },
      { title: 'Money Page', href: '/hoc-phi', body: 'Diem ve thuong mai phu hop sau khi so sanh.' },
    ],
  },
  {
    slug: 'class-ai-ready-faq',
    classCode: 'Class 11',
    templateClass: 'AI-Ready FAQ / Answer Engine',
    group: 'Mid-funnel / Nurturing',
    theme: 'nurture',
    pageRole: 'Tra loi PAA, AI Overview va voice search',
    description:
      'FAQ engine phai de doc, de scan, de goi tiep khi can. No khong chi de giam call trung lap ma con de tro thanh mot lop discoverability rat manh.',
    audience: 'Phu huynh can cau tra loi nhanh, ro va minh bach',
    funnel: 'TOFU / MOFU / BOFU nhe',
    traffic: 'Organic PAA, voice search, support traffic, AI citations',
    cvr: '3-6%',
    primaryCta: 'Goi ngay de duoc giai dap sau hon',
    secondaryCta: 'Nhan Zalo tu van',
    sampleHeadline: 'FAQ page khong duoc la bai chu da thich. No phai co cau truc, co tab va co CTA dung luc.',
    sampleBody:
      'Template nay phai giu tone calm confidence. Moi cau tra loi nen ngan, ro, khong ne cau hoi kho va co duong di tiep theo rat tu nhien.',
    previewHighlights: [
      'Tab theo chu de de giam tai nhan thuc.',
      'Accordion ngan gon, de scan tren mobile.',
      'CTA duoi moi nhom cau hoi giup chuyen doi mem.',
      'FAQPage schema la lop SEO quan trong.',
    ],
    blockOrder: [
      'Quick answer hero.',
      'Tabbed accordion.',
      'CTA duoi tung nhom cau hoi.',
      'Short form / contact fallback.',
      'Related hubs / pillars.',
    ],
    brandRules: [
      'Tra loi bang giong minh bach, binh tinh va co logic.',
      'Khong ne cau hoi hoc phi, khoang cach, hoa nhap, ap luc.',
      'Khong do blame len phu huynh khi ho dang lo lang.',
      'Van giu voice am ap va huu ich.',
    ],
    seoRules: [
      'Can title ro nghia va heading theo y dinh tim kiem.',
      'FAQPage schema la uu tien cao.',
      'Internal links toi pillar, money page va admissions hub.',
      'Accordion content can van nam trong HTML de crawl tot.',
    ],
    enhancementIdeas: [
      'Them search noi bo cho FAQ hub lon.',
      'Map cau hoi theo level, hoc phi, campus, admissions.',
      'Lay data cau hoi tu admissions / Zalo de cap nhat dinh ky.',
    ],
    internalLinks: [
      { title: 'Admissions Hub', href: '/tuyen-sinh', body: 'Diem chot tiep theo khi FAQ khong du de giai quyet.' },
      { title: 'Money Page', href: '/hoc-phi', body: 'Phu hop voi nhom FAQ xoay quanh hoc phi.' },
      { title: 'Parent Hub Article', href: '/mau-template/class-parent-hub-article/', body: 'Layer noi dung sau hon cho nhung chu de can giai thich dai.' },
    ],
  },
  {
    slug: 'class-homepage',
    classCode: 'Class 12',
    templateClass: 'Homepage / Grand Central Station',
    group: 'System / Utility',
    theme: 'system',
    pageRole: 'Dieu phoi traffic va dong bo positioning',
    description:
      'Homepage sample cho thay mot trang chu dung vai tro brand router. No khong phai mot banner dep, ma la trang sap xep user vao dung level, dung campus, dung CTA.',
    audience: 'Moi phu huynh vao tu brand search, direct, referral',
    funnel: 'All funnel',
    traffic: 'Branded search, direct, referrals',
    cvr: '2-4%',
    primaryCta: 'Dang ky tu van',
    secondaryCta: 'Chon cap hoc / khu vuc',
    sampleHeadline: 'Homepage dung chuan se noi ro Viet Anh la ai trong 5-7 giay dau, roi dieu huong user den dung hanh dong.',
    sampleBody:
      'Class Homepage can gan toan bo positioning: lien cap, chuyen Anh, hanh phuc, thuc dung, tu chu. No phai co quick filter, proof, route cards va CTA nhe nhung ro.',
    previewHighlights: [
      'Hero ngan, ro positioning va co quick routing.',
      'Stats / proof / level navigation phai dat som.',
      'Khong duoc nhung qua nhieu thong diep cung luc.',
      'Homepage phai giu duoc can bang brand va conversion.',
    ],
    blockOrder: [
      'Hero + quick filter.',
      'Stats / proof.',
      'Level navigation.',
      'Campus selector / route cards.',
      'News / event highlights.',
      'Main CTA + FAQ compact.',
    ],
    brandRules: [
      'Homepage phai noi giong thuong hieu ro nhat.',
      'Khong lam thanh brochure hay noi toan slogan rong.',
      'Visual phai co sinh khi that, hoc sinh that, campus that.',
      'CTA nhe ma ro, khong qua sale.',
    ],
    seoRules: [
      'Title / description phai positioning dung thuong hieu.',
      'Heading hierarchy can rat sach.',
      'Internal links toi pillars, admissions, money page va template listing / campaigns.',
      'Hero media phai nhe de homepage van nhanh.',
    ],
    enhancementIdeas: [
      'Them quick filter that su theo level + location o production.',
      'Them event strip dong tu Directus cho campaign theo mua.',
      'Bo sung visual “student presenting to parents” nhu signature narrative asset.',
    ],
    internalLinks: [
      { title: 'Homepage live', href: '/', body: 'Trang chu wave 1 dang live tren staging.' },
      { title: 'Template listing', href: '/mau-template/', body: 'Danh muc 16 sample templates de doi team review.' },
      { title: 'Admissions Hub', href: '/tuyen-sinh', body: 'Hub conversion chinh duoc homepage route vao.' },
    ],
  },
  {
    slug: 'class-smart-thank-you',
    classCode: 'Class 13',
    templateClass: 'Smart Thank-You Page',
    group: 'System / Utility',
    theme: 'system',
    pageRole: 'Giu lead nong va day next-step sau submit',
    description:
      'Thank-you page sample cho thay cach giu nhiet lead, fire tracking va route sang hanh dong tiep theo. Day la page hay bi lam so sai nhat.',
    audience: 'Nguoi vua submit form hoac vua dang ky',
    funnel: 'Post-conversion',
    traffic: 'Post-submit flows',
    cvr: '15-25% next-step',
    primaryCta: 'Dat lich tham quan',
    secondaryCta: 'Nhan Zalo / tai tai lieu',
    sampleHeadline: 'Thank-you page khong duoc ket thuc trai nghiem. No phai mo ra buoc tiep theo ro rang va huu ich.',
    sampleBody:
      'Class nay cuc ky quan trong cho performance va CRM. Neu lam tot, no tang quality cua lead ngay sau submit ma khong can spam. Neu lam kem, no bo roi user cho sales.',
    previewHighlights: [
      'Thank-you message can am, gon va ro buoc tiep theo.',
      'Next-step blocks phai theo loai form vua submit.',
      'Pixel fire va event tracking can chinh xac.',
      'Nen co video / trust nhe de giu nhiet lead.',
    ],
    blockOrder: [
      'Thank-you headline va dynamic context.',
      'Next-step blocks theo form type.',
      'Trust / video ngan.',
      'Hidden tracking / conversion event block.',
      'Optional support links.',
    ],
    brandRules: [
      'Giong cham soc, khong spam, khong “ban tiep” qua gap.',
      'Loi hua phan hoi phai thuc te.',
      'Trang nay phai cho thay su chuyen nghiep va chu dao.',
      'Khong bo trong man hinh voi chi 1 cau “cam on”.',
    ],
    seoRules: [
      'Vi la page hau submit, production nen can nhac noindex.',
      'Can tracking events ro rang hon la SEO traffic.',
      'URL / title van nen ro nghia theo form type.',
      'Khong can nhieu internal links lam loang next-step.',
    ],
    enhancementIdeas: [
      'Ca nhan hoa theo campus, level, form type.',
      'Them QR / deep link vao Zalo group theo campus.',
      'Tieptuc dong bo voi GHL workflow de gui PDF / nhac lich tu dong.',
    ],
    internalLinks: [
      { title: 'Campus Tour', href: '/mau-template/class-b-campus-tour/', body: 'Next-step rat hop ly cho lead fee / consultation.' },
      { title: 'Admissions Hub', href: '/tuyen-sinh', body: 'Fallback khi user muon doc lai quy trinh.' },
      { title: 'Homepage', href: '/', body: 'Chi nen cho phep ve homepage rat nhe, khong nen la CTA chinh.' },
    ],
  },
  {
    slug: 'class-dynamic-comparison',
    classCode: 'Class 14',
    templateClass: 'Dynamic Comparison Page',
    group: 'System / Utility',
    theme: 'system',
    pageRole: 'Scale nhieu page so sanh bang data dong',
    description:
      'Template nay gan voi Comparison Engine nhung dat nang hon vao kha nang scale thong qua data tu CMS. No phai co narrative va governance, khong chi la table dong.',
    audience: 'Phu huynh va doi team can mo rong nhieu page so sanh',
    funnel: 'MOFU',
    traffic: 'SEO comparison, internal linking, sales enablement',
    cvr: '4-7%',
    primaryCta: 'Nhan tu van de chon phu hop',
    secondaryCta: 'Xem page so sanh gan',
    sampleHeadline: 'So sanh dong chi huu ich khi du lieu duoc quan ly ky va moi page van giu duoc giong thuong hieu.',
    sampleBody:
      'Class nay duoc thiet ke cho giai doan scale. CMS se bom data vao table nhung page van can opening copy, unique points, FAQ va CTA ro rang de khong tro thanh table vo hon.',
    previewHighlights: [
      'Data-driven nhung van can narrative mo dau.',
      'Table can responsive, co governance va cap nhat dinh ky.',
      'Can unique angle cho tung page so sanh.',
      'CTA va internal links phai ro nhu comparison engine thuong.',
    ],
    blockOrder: [
      'Hero / opening narrative.',
      'Dynamic comparison table.',
      'Unique points / interpretation.',
      'FAQ va CTA.',
      'Related comparisons.',
    ],
    brandRules: [
      'Chinh truc trong data la bat buoc.',
      'Khong dung dynamic scale de xuat ban hang loat noi dung chat luong thap.',
      'Voice van phai calm confidence.',
      'Noi su khac biet bang proof, khong bang tu khoa truong.',
    ],
    seoRules: [
      'Moi page dynamic van can title / meta / intro unique.',
      'Tranh thin content va duplicate headings.',
      'Internal links giua cluster comparison pages can co chu dich.',
      'Schema / structured data co the them o phase sau neu table on dinh.',
    ],
    enhancementIdeas: [
      'Them workflow review competitor data hang quy.',
      'Cache / snapshot so sanh de tranh stale khong kiem soat.',
      'Cho phep an hien rows tren mobile theo interest cua phu huynh.',
    ],
    internalLinks: [
      { title: 'Comparison Engine', href: '/mau-template/class-comparison-engine/', body: 'Ban “manual” can bang giua narrative va comparison.' },
      { title: 'Money Page', href: '/hoc-phi', body: 'Diem sang thuong mai hop ly sau khi so sanh.' },
      { title: 'Admissions Hub', href: '/tuyen-sinh', body: 'Diem chot hanh dong tiep theo.' },
    ],
  },
  {
    slug: 'class-objection-handler',
    classCode: 'Class 15',
    templateClass: 'Objection Handler Page',
    group: 'System / Utility',
    theme: 'system',
    pageRole: 'Go cac phan doi nhu hoc phi, nha xa, be nhut nhat',
    description:
      'Template nay giai quyet nhung cau hoi kho nhat bang giọng binh tinh, co logic va co proof. Day la noi thuong hieu the hien su chinh truc rat ro.',
    audience: 'Phu huynh da gan ra quyet dinh nhung van con lo lang',
    funnel: 'MOFU / BOFU',
    traffic: 'Retargeting, sales follow-up, organic objection queries',
    cvr: '6-10%',
    primaryCta: 'Nhan tu van phu hop',
    secondaryCta: 'Dang ky hoc thu / tham quan',
    sampleHeadline: 'Objection page tot khong tranh cau hoi kho. No giup phu huynh binh tam hon va quyet dinh tinh tao hon.',
    sampleBody:
      'Template nay co the rat manh neu duoc viet dung giong: minh bach, logic, khong phong thu. Neu viet sai, no se tro thanh page “giai thich quanh co” va lam mat trust.',
    previewHighlights: [
      'Hero can goi dung noi lo that, khong nao long user.',
      'Accordion objections nen co proof kem theo.',
      'CTA phai dan sang buoc giai quyet phu hop nhat.',
      'Sales co the gui link page nay trong qua trinh follow-up.',
    ],
    blockOrder: [
      'Pain-point hero.',
      'Objection accordion.',
      'Proof block / testimonial.',
      'CTA call / Zalo / trial / tour.',
      'Related resources.',
    ],
    brandRules: [
      'Binh tinh, minh bach va khong defensive.',
      'Noi thang vao cau hoi kho, khong ne tranh.',
      'Dung proof that, vi du that, khong khoe rong.',
      'Van giu tone am va ton trong phu huynh.',
    ],
    seoRules: [
      'Title / H1 co the bat objection intent ro rang.',
      'Can internal links sang fee, trial, tour, campus tuong ung.',
      'Structured FAQ co the huu ich neu page dung accordion.',
      'Page nen co intro unique va khong qua ngan de tranh thin content.',
    ],
    enhancementIdeas: [
      'Tao cluster objection pages theo 4-5 noi lo lon nhat.',
      'Dong bo voi FAQ engine de tranh noi dung trung lap vo ich.',
      'Them proof video ngan cho objection ve hoa nhap hoac ap luc hoc.',
    ],
    internalLinks: [
      { title: 'Trial Class', href: '/mau-template/class-d-trial-class/', body: 'Giai phap tot cho objection “be nhut nhat”.' },
      { title: 'Money Page', href: '/hoc-phi', body: 'Diem tiep theo cho objection lien quan hoc phi.' },
      { title: 'Campus Tour', href: '/mau-template/class-b-campus-tour/', body: 'Giai phap hop ly cho objection “muon xem truong that”.' },
    ],
  },
  {
    slug: 'class-retention-referral',
    classCode: 'Class 16',
    templateClass: 'Retention & Referral Page',
    group: 'System / Utility',
    theme: 'system',
    pageRole: 'Tang LTV qua referral, loyalty va event upsell',
    description:
      'Sample retention page nhac rang website khong chi dung o admissions. Sau khi nhap hoc, brand voice van can tiep tuc ro, am va chuyen nghiep.',
    audience: 'Phu huynh hien tai trong he thong Viet Anh',
    funnel: 'Post-enrollment / loyalty',
    traffic: 'Email, Zalo CRM, internal communications',
    cvr: '8-12%',
    primaryCta: 'Gioi thieu ban be',
    secondaryCta: 'Dang ky su kien / trai nghiem tiep',
    sampleHeadline: 'Retention page tot giu duoc cam giac duoc cham soc, khong bien phu huynh hien tai thanh target bi ban hang.',
    sampleBody:
      'Template nay dung cho referral va loyalty. No phai rat ro phan thuong, rat ro loi ich va van giu duoc tinh te cua thuong hieu giao duc.',
    previewHighlights: [
      'Thong diep cam on va ghi nhan phai di truoc.',
      'Referral form gon, khong doi qua nhieu thong tin.',
      'Loyalty offer phai ro, khong mo ho.',
      'CTA event / summer camp la huong mo rong LTV hop ly.',
    ],
    blockOrder: [
      'Retention thank-you hero.',
      'Referral form block.',
      'Loyalty offer / explanation.',
      'Event CTA / summer camp CTA.',
      'Support info / FAQ ngan.',
    ],
    brandRules: [
      'Am, ro, chuyen nghiep va ton trong phu huynh hien tai.',
      'Khong qua salesy vi day la giai doan loyalty.',
      'Neu co phan thuong, phai noi ro va minh bach.',
      'Van giu mot giong thong nhat voi homepage va admissions.',
    ],
    seoRules: [
      'Phan lon traffic se den tu CRM nen SEO khong phai uu tien so 1.',
      'Neu page public, van can title / description ro nghia.',
      'Can can nhac noindex tuy theo role cua page.',
      'CTA phai it va rat muc tieu.',
    ],
    enhancementIdeas: [
      'Noi vao GHL workflow referral tracking va reward status.',
      'Them history / dashboard nhe cho phu huynh neu san pham phat trien sau nay.',
      'Phan tan theo campus neu loyalty offers khac nhau.',
    ],
    internalLinks: [
      { title: 'Open Day / Event', href: '/mau-template/class-c-open-day/', body: 'Vi du ve event CTA co the noi vao retention.' },
      { title: 'Smart Thank-You', href: '/mau-template/class-smart-thank-you/', body: 'Lien ket quan trong trong he thong post-conversion.' },
      { title: 'Homepage', href: '/', body: 'Neu can quay lai trang thuong hieu me.' },
    ],
  },
];

export const templateGroups = [
  'Performance',
  'SEO / Authority',
  'Mid-funnel / Nurturing',
  'System / Utility',
] as const;

export function getTemplateSampleBySlug(slug: string) {
  return templateSamples.find((sample) => sample.slug === slug);
}
